M48
; DRILL file {KiCad 9.0.1} date 2025-08-04T14:54:05+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-04T14:54:05+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0728
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X4.785Y-4.3096
X4.785Y-4.5006
T2
X4.9043Y-4.2978
X4.9043Y-4.5124
M30
